builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_arm64
    main: ./cmd/plugin-registry-update/
    binary: plugin-registry-update
    flags:
      - -trimpath
    ldflags:
      - -extldflags '-static'
      - -s -w -X main.version={{.Version}}

archives:
  - format: binary
    name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'
