name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'cloud-firestore-emulator'
      - run: go test -v ./...
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: google-github-actions/auth@v1
        with:
          project_id: go-semantic-release
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
        if: steps.semrel.outputs.version != ''
      - uses: google-github-actions/setup-gcloud@v1
        if: steps.semrel.outputs.version != ''
      - run: ./scripts/docker-build-and-push.sh ${{ steps.semrel.outputs.version }}
        if: steps.semrel.outputs.version != ''
      - uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: staging-plugin-registry
          region: europe-west1
          image: gcr.io/go-semantic-release/plugin-registry:${{ steps.semrel.outputs.version }}
        if: steps.semrel.outputs.version != ''
