name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go generate ./...
      - uses: golangci/golangci-lint-action@v3
        with:
          skip-pkg-cache: true
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'cloud-firestore-emulator'
      - run: go generate ./...
      - run: go test -v ./...
  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: go-semantic-release
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
        if: steps.semrel.outputs.version != ''
      - run: gcloud auth configure-docker gcr.io -q
        if: steps.semrel.outputs.version != ''
      - run: ./scripts/docker-build-and-push.sh ${{ steps.semrel.outputs.version }}
        if: steps.semrel.outputs.version != ''
      - uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: staging-plugin-registry
          image: gcr.io/go-semantic-release/plugin-registry:${{ steps.semrel.outputs.version }}
        if: steps.semrel.outputs.version != ''
